### ISSUE TITLE
htc_r50_fpn_1x_nuim.py 文件找不到

### ISSUE THREAD

**Issue by daxiongpro** [BraveGroup/FullySparseFusion#5]
作者你好，在做第一步：./tools/mask_tools/save_mask_nusc.sh 的时候，先分割网络的 _base_ = './htc_r50_fpn_1x_nuim.py'
这个 htc_r50_fpn_1x_nuim.py 文件没提供，能提供一下嘛？

**Comment by liyingyanUCAS** [comment]
We include these configs in the latest commit. Please use the latest code (no need to reinstall the environment) and then directly run ./tools/mask_tools/save_mask_nusc.sh. Then everything should work as expected.

**Comment by daxiongpro** [comment]
Thank you for your quick response. This is a great and outstanding work!
