### ISSUE TITLE
FormatCode 问题

### ISSUE THREAD

**Issue by daxiongpro** [BraveGroup/FullySparseFusion#6]
You wrote in README:
```
      #text, _ = FormatCode(text, style_config=yapf_style, verify=True)
      text, _ = FormatCode(text, style_config=yapf_style)
```
I also encountered this issue in another project, which is actually due to the high version of yapf. Just downgrade the yapf version to 0.40.1.

```
pip install yapf==0.40.1
```
No need to modify the source code of mmcv.

**Comment by liyingyanUCAS** [comment]
Thank you for your valuable advice！
