### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/argo2/kitti_format/training/velodyne/0011005.bin'

### ISSUE THREAD

**Issue by perfectddt** [BraveGroup/FullySparseFusion#7]
我在采用网盘里的pkl文件，运行av2数据集的时候，下载kitti数据集的的data_object_velodyne里是没有这个文件。我应该是下载kitti里的什么数据集，又或者如何处理这个问题?麻烦了。

**Comment by curiosity654** [comment]
@liyingyanUCAS Same problem here, could you please give any further instructions?

**Comment by curiosity654** [comment]
Also is there any script to generate gt database for Argo2?

**Comment by liyingyanUCAS** [comment]
You can use scripts from https://github.com/tusen-ai/SST/tree/main/tools/argo

**Comment by curiosity654** [comment]
Many thanks for your reply!
